### ISSUE TITLE
Settings.current

### ISSUE THREAD

**Issue by dreamfall** [bitzesty/qae#279]
@matthewford @jaleszek @RuslanHamidullin  

We use `Settings.current` to get current settings for the application. 

```ruby
  def self.for_year(year)
    where(year: year).first_or_create
  end

  def self.current
    for_year(Date.current.year)
  end
```

The problem is that applications are being processed for a period that covers two years so we can not just use `Date.current.year`. Otherwise all settings that've been set up now won't be used after 01.01.2016. 
We need to think of the way of detecting what award year is it. 

@matthewford @jaleszek @RuslanHamidullin

**Comment by matthewford** [comment]
Can we not set the year when the user creates the application?

**Comment by RuslanHamidullin** [comment]
@dreamfall @jaleszek @matthewford 
maybe we should use calculated year instead of
```
Date.current.year
```

Award year is starts at 21 April.
```
now = Time.now
21_april_this_year = DateTime.new(now.year, 4, 21)

if now >=  21_april_this_year
  Date.current.year + 1
else
  Date.current.year
end
```

So, before 21 april - will be current year (2015)
After 21 april - will be next year 2016

**Comment by dreamfall** [comment]
@RuslanHamidullin I thought about that but we need to be sure that there will be no notifications after the 21st of April for previous awards.

**Comment by matthewford** [comment]
@dreamfall @RuslanHamidullin can close this now right, with the refactoring of the years?

**Comment by dreamfall** [comment]
@matthewford I guess no. We should leave it until we do the switch between award years in admin area (in the menu).
