### ISSUE TITLE
Remove all the landing page content that will transition to the gov.uk guide

### ISSUE THREAD

**Issue by matthewford** [bitzesty/qae#287]
`if landing_page`

**Comment by matthewford** [comment]
Hold off on this toll Laura reviews copy to send to gds

**Comment by matthewford** [comment]
@hammerfunk are the static content pages removed (i know we've done the redirects)

**Comment by hammerfunk** [comment]
not yet

**Comment by matthewford** [comment]
@hammerfunk if you are not doing anything we should begin to tidy up - remove all static content that is on gov.uk (not the app) and any placeholder stuff.

**Comment by hammerfunk** [comment]
ok will do

**Comment by hammerfunk** [comment]
Removed in this commit
https://github.com/bitzesty/qae/commit/32a3998c16f28fcbf298712644ca5edb43cbca64
