### ISSUE TITLE
DEV TASK: Forms. Need to make dates displaying dynamicly

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#318]
In A5 and A6 dates are displaying are hardcoded.
![make_dates_in_a5_a6_dynamic](https://cloud.githubusercontent.com/assets/358508/7105878/fc74ada6-e136-11e4-8934-5468282c88ab.png)

**Comment by matthewford** [comment]
@hammerfunk @RuslanHamidullin still an issue?

**Comment by hammerfunk** [comment]
Nope
