### ISSUE TITLE
VIRUS SCANNER TASK: bugfixes and testing

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#337]
Bug:
after_save :virus_scan unless ENV["DISABLE_VIRUS_SCANNER"] == "true"

so, for local / dev / demo servers - which we are not setting up with Virus Scanner Connection
- scans woudn't be created
It should create Scan model with "clean" state in case if ENV["DISABLE_VIRUS_SCANNER"] == "true"

Also, I think would be worth to double check / test:
1) Upload of Form attachment's
2) Upload of Support Letters for Enterprise Promotion Form
3) Uploads of audit certificate on localhost:3000/users/form_answers/<ID>/audit_certificate
4) And then make sure that Scan models are created if ENV["DISABLE_VIRUS_SCANNER"] == "true"
     and that scan.clean condition works properly on admin side admin/form_answers/<ID>

**Comment by meal** [comment]
@RuslanHamidullin could you please check manually if this works on your side?

**Comment by RuslanHamidullin** [comment]
@meal nope, I have quate lot todos

**Comment by matthewford** [comment]
@RuslanHamidullin I'll take a look
