### ISSUE TITLE
CONFIRM WITH MICHAEL: do we need to make Dashboard / "Switch View" section work without JS

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#357]
Do we need to make Dashboard / "Switch View" section work without JS?

**Comment by hammerfunk** [comment]
The switch view button is for debugging, It's not visible outside of dev.
I put it there so we can see the post submission dashboard easily as devs.
In the future, the app would just switch automatically to the post submission dashboard after the submission deadline is reached.

**Comment by matthewford** [comment]
Should probably remove

**Comment by RuslanHamidullin** [comment]
@hammerfunk ok closing issue
