### ISSUE TITLE
Clean up orphaned files which are removed from form.

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#358]
@matthewford 
Currently we do not remove form attachment files (stored in FormAnswerAttachment) if it removed from Form.
It explained as we need to click "Save and Continue" on JS form in order to apply removing attachment from Form document hash.

Looks like we need to remove unused FormAnswerAttachments's via for example cron task?

**Comment by matthewford** [comment]
Think we need to discuss this.

**Comment by RuslanHamidullin** [comment]
@matthewford gonna take a look to this one.
So possible ways to solve:
1) Add cron script, which would clean up Attachments related to forms, but not saved in document of form (probably weekly)
2) Add ajax removing of attachments on click "Remove"

**Comment by matthewford** [comment]
think step 2) would be preferable, although when you say ajax I assume you mean a way with a non-js fallback?

**Comment by RuslanHamidullin** [comment]
In non - js version already implemented removing of attachment

**Comment by RuslanHamidullin** [comment]
Ok, gonna add removing of attachment via AJAX for JS version
