### ISSUE TITLE
DEV TASK: International Form C1

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#366]
RE:
```
"14) C1 – In answer to question A6 I chose ‘International Trade (3 years) 2014.’ When I came to CI the message that came up “As you currently hold a Queen's Award for Continuous Achievement in International Trade (3 years), you can only apply for the Outstanding Achievement Award (6 years). “ – this is factually incorrect
i)        It does not matter whether the applicant holds a 3 or 6 year International Trade Award from the Award years 2012 to 2015 inclusive - they can only apply for the 2016 Awards on the basis of an “Outstanding achievement” entry i.e. a 3 year submission.
ii)        If the application is submitted and it is the final year of an existing Award, ie for 2016 an Award made in 2011, they are eligible to enter on a continuous basis.
"
```

Declaration:
https://github.com/bitzesty/qae/blob/master/app/forms/qae_2014_forms/international_trade/international_trade_step3.rb#L14

Options which used for conditional placeholder is:
"placeholder_preselected_condition"

Class:
https://github.com/bitzesty/qae/blob/master/lib/qae_form_builder/options_with_preselected_conditions_question.rb

View that handles it:
https://github.com/bitzesty/qae/blob/master/app/views/qae_form/_options_with_preselected_conditions_question.html.slim

JS which do switching:
https://github.com/bitzesty/qae/blob/master/app/assets/javascripts/frontend/custom_questions/options_with_preselected_conditions_question.js.coffee

Basicly: 
```
in "A 6.1" you can set list of current awards
if you set "Trade (6 years)"
JS displays:
"As you currently hold a Queen's Award for Continuous Achievement in International Trade (6 years), you can only apply for the Outstanding Achievement Award (3 years)"
```
Initially here was another "vie versa" condition, but now only one

**Comment by matthewford** [comment]
@RuslanHamidullin still an issue? Not clear on what the issue is atm...

**Comment by RuslanHamidullin** [comment]
@matthewford I remember that @jaleszek worked on it last time. Does it @jaleszek ?

**Comment by jaleszek** [comment]
all good

**Comment by RuslanHamidullin** [comment]
:+1:
