### ISSUE TITLE
FOR DEVS: Random issue with HTML input name replacement (on Support Letters, probably can cause in other places too) 

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#377]
We got it multiple times randomly, mostly on local.
we have declarated in Form DSL:
```
options :manually_upload, "Would you like to manually upload any of your letters of support?" do
   ref "D 2"
end

supporters :supporter_letters_list, "Manual upload" do
   limit 4
   default 1
    list_type :manuall_upload
    conditional :manually_upload, :yes
end
```

Sometimes we getting that name of "form[manual_upload]" changing to "form[supporter_letters_list]".
Sometimes it can be reproduced (but very - very rarely):
```
1) go to EP form
2) Add 1 supporter
3) save and continue
4) then go back to step 4
5) select No in manual upload question
```

And:
```
won't go away until the server is restarted
and when it's gone it's impossible to reproduce
```

We are suppose that question input_name is cached in ruby, like:
```
def var
  @var ||= smth
end
```

Cause it's global for all the forms.
It's so elusive, but it can potentially break the EP form.

**Comment by RuslanHamidullin** [comment]
Hey guys, we already got this error on local with @dreamfall in different times.
@jaleszek @matthewford any thoughts?

**Comment by matthewford** [comment]
yeah well we'll need to find / fix this issue before by end of day monday

**Comment by dreamfall** [comment]
ref https://github.com/bitzesty/qae/issues/371
