### ISSUE TITLE
Support Letters: in JS and NON JS versions are displaying different number of SupportLetters

### ISSUE THREAD

**Issue by RuslanHamidullin** [bitzesty/qae#417]
Today I'm added virus scanner conditions to displaying of file links (to supporter letters too), and by the way tested JS / NON Js support letters.
In JS and NON JS versions are displaying different number of SupportLetters.
I'm not sure, but probably need to corrects smth for NON JS in saving mechanizms

**Comment by RuslanHamidullin** [comment]
Rails console:
```
2.1.5 :018 > FormAnswer.last.document["support_letters_list"]
  FormAnswer Load (0.8ms)  SELECT  "form_answers".* FROM "form_answers"  ORDER BY "form_answers"."id" DESC LIMIT 1
 => nil 
2.1.5 :019 > FormAnswer.last.support_letters.count
  FormAnswer Load (0.8ms)  SELECT  "form_answers".* FROM "form_answers"  ORDER BY "form_answers"."id" DESC LIMIT 1
   (0.4ms)  SELECT COUNT(*) FROM "support_letters" WHERE "support_letters"."form_answer_id" = $1  [["form_answer_id", 22]]
 => 4 
```

**Comment by RuslanHamidullin** [comment]
Here JS ans NON JS screens 
![js_screen](https://cloud.githubusercontent.com/assets/358508/7272600/d03b2ce0-e8f4-11e4-85c2-4f4f0f39e9d4.png)
![non_js_screen](https://cloud.githubusercontent.com/assets/358508/7272606/d6e81738-e8f4-11e4-96a8-0a1173c0f42a.png)

**Comment by dreamfall** [comment]
Fix is in master.
