### ISSUE TITLE
We're receiving a lot pseudo-random errors on Travis.

### ISSUE THREAD

**Issue by jaleszek** [bitzesty/qae#431]
I propose to collect info about not stable tests in terms of CI, to gain better insight into problem and think out generic solution.

**Comment by jaleszek** [comment]
Failures:
  1) Admin comments management 
As a Admin
I want to be able to view, create and destroy the comments per application.
 adding flags Critical comments adds flag to created comment
     Failure/Error: Unable to find matching line from backtrace
     ActiveRecord::RecordNotFound:
       Couldn't find FormAnswer with 'id'=6 [WHERE "form_answers"."award_year_id" = ?]
     # ./app/controllers/concerns/form_answer_flags_mixin.rb:33:in `form_answer'
     # ./app/controllers/concerns/form_answer_flags_mixin.rb:6:in `toggle'
Finished in 4 minutes 33.8 seconds (files took 5.37 seconds to load)
346 examples, 1 failure

**Comment by jaleszek** [comment]
Failures:
  1) Creating application forms I'm able to create innovation form When I create innovation form -> Then I should see qae form -> And I should see application edit link on dashboard
     Failure/Error: When I create innovation form
     Capybara::ElementNotFound:
       Unable to find link "New application" with href "/apply_innovation_award"
     # spec/acceptance/steps/application_form_creation_steps.rb:32:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:13:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:14:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:13:in `each'
     # ./spec/acceptance/application_form_creation.feature:13:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:13:in `I create innovation form'
  2) Creating application forms I see application links on dashboard When I go to dashboard -> Then I should see innovation application link -> And I should see international trade application link -> And I should see sustainable development application link
     Failure/Error: Then I should see innovation application link
       expected to find link "New application" with href "/apply_innovation_award" but there were no matches
     # spec/acceptance/steps/application_form_creation_steps.rb:19:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:8:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:8:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:7:in `each'
     # ./spec/acceptance/application_form_creation.feature:7:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:8:in `I should see innovation application link'
  3) Creating application forms I'm able to create international trade form When I create international trade form -> Then I should see qae form -> And I should see application edit link on dashboard
     Failure/Error: When I create international trade form
     Capybara::ElementNotFound:
       Unable to find link "New application" with href "/apply_international_trade_award"
     # spec/acceptance/steps/application_form_creation_steps.rb:39:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:18:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:19:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:18:in `each'
     # ./spec/acceptance/application_form_creation.feature:18:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:18:in `I create international trade form'
  4) Creating application forms I'm able to create sustainable development form When I create sustainable development form -> Then I should see qae form -> And I should see application edit link on dashboard
     Failure/Error: When I create sustainable development form
     Capybara::ElementNotFound:
       Unable to find link "New application" with href "/apply_sustainable_development_award"
     # spec/acceptance/steps/application_form_creation_steps.rb:46:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:23:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:24:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:23:in `each'
     # ./spec/acceptance/application_form_creation.feature:23:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:23:in `I create sustainable development form'
Finished in 5 minutes 2 seconds (files took 7.01 seconds to load)
359 examples, 4 failures, 4 pending

**Comment by jaleszek** [comment]
Failures:
  1) FormAnswerStateMachine#trigger_deadlines deadline expired applications submitted automatically changes state to `assessment_in_progress`
     Failure/Error: expect {
       expected result to have changed from "submitted" to "assessment_in_progress", but did not change
     # ./spec/models/form_answer_state_machine_spec.rb:25:in `block (5 levels) in <top (required)>'
  2) FormAnswerStateMachine#trigger_deadlines deadline expired applications in progress automatically changes state to `not_submitted`
     Failure/Error: expect {
       expected result to have changed from "application_in_progress" to "not_submitted", but did not change
     # ./spec/models/form_answer_state_machine_spec.rb:35:in `block (5 levels) in <top (required)>'
Finished in 4 minutes 56.6 seconds (files took 5.83 seconds to load)
359 examples, 2 failures, 4 pending

**Comment by jaleszek** [comment]
Failures:
  1) Admin fulfills the company details can see the edit buttons
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `deadlines' for nil:NilClass
     # ./app/controllers/application_controller.rb:158:in `load_award_year_and_settings'
  2) Creating application forms I'm able to create sustainable development form When I create sustainable development form -> Then I should see qae form -> And I should see application edit link on dashboard
     Failure/Error: When I create sustainable development form
     Capybara::ElementNotFound:
       Unable to find link "New application" with href "/apply_sustainable_development_award"
     # spec/acceptance/steps/application_form_creation_steps.rb:46:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:23:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:24:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:23:in `each'
     # ./spec/acceptance/application_form_creation.feature:23:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:23:in `I create sustainable development form'
  3) Creating application forms I see application links on dashboard When I go to dashboard -> Then I should see innovation application link -> And I should see international trade application link -> And I should see sustainable development application link
     Failure/Error: Then I should see innovation application link
       expected to find link "New application" with href "/apply_innovation_award" but there were no matches
     # spec/acceptance/steps/application_form_creation_steps.rb:19:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:8:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:8:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:7:in `each'
     # ./spec/acceptance/application_form_creation.feature:7:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:8:in `I should see innovation application link'
  4) Creating application forms I'm able to create international trade form When I create international trade form -> Then I should see qae form -> And I should see application edit link on dashboard
     Failure/Error: When I create international trade form
     Capybara::ElementNotFound:
       Unable to find link "New application" with href "/apply_international_trade_award"
     # spec/acceptance/steps/application_form_creation_steps.rb:39:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:18:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:19:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:18:in `each'
     # ./spec/acceptance/application_form_creation.feature:18:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:18:in `I create international trade form'
  5) Creating application forms I'm able to create innovation form When I create innovation form -> Then I should see qae form -> And I should see application edit link on dashboard
     Failure/Error: When I create innovation form
     Capybara::ElementNotFound:
       Unable to find link "New application" with href "/apply_innovation_award"
     # spec/acceptance/steps/application_form_creation_steps.rb:32:in `block in <top (required)>'
     # ./spec/acceptance/application_form_creation.feature:13:in `run_step'
     # ./spec/acceptance/application_form_creation.feature:14:in `block (6 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:13:in `each'
     # ./spec/acceptance/application_form_creation.feature:13:in `block (5 levels) in run'
     # ./spec/acceptance/application_form_creation.feature:13:in `I create innovation form'
  6) FormAnswerStateMachine#perform_transition after the deadline as Assessor can change state only to allowed
     Failure/Error: expect(form_answer.reload.state).to eq("not_submitted")
       
       expected: "not_submitted"
            got: "application_in_progress"
       
       (compared using ==)
     # ./spec/models/form_answer_state_machine_spec.rb:73:in `block (5 levels) in <top (required)>'
  7) FormAnswerStateMachine#trigger_deadlines deadline expired applications in progress automatically changes state to `not_submitted`
     Failure/Error: expect {
       expected result to have changed from "application_in_progress" to "not_submitted", but did not change
     # ./spec/models/form_answer_state_machine_spec.rb:54:in `block (5 levels) in <top (required)>'
  8) FormAnswerStateMachine#trigger_deadlines deadline expired assessment_in_progress -> withdrawn sends notification for the Lead Assessor
     Failure/Error: expect(form_answer.reload.state).to eq("withdrawn")
       
       expected: "withdrawn"
            got: "assessment_in_progress"
       
       (compared using ==)
     # ./spec/models/form_answer_state_machine_spec.rb:37:in `block (5 levels) in <top (required)>'
  9) FormAnswerStateMachine#trigger_deadlines deadline expired applications submitted automatically changes state to `assessment_in_progress`
     Failure/Error: expect {
       expected result to have changed from "submitted" to "assessment_in_progress", but did not change
     # ./spec/models/form_answer_state_machine_spec.rb:44:in `block (5 levels) in <top (required)>'
Finished in 5 minutes 15 seconds (files took 5.34 seconds to load)
369 examples, 9 failures, 4 pending
Failed examples:
rspec ./spec/features/admin/form_answers/admin_fulfills_company_details_spec.rb:33 # Admin fulfills the company details can see the edit buttons
rspec ./spec/acceptance/application_form_creation.feature:22 # Creating application forms I'm able to create sustainable development form When I create sustainable development form -> Then I should see qae form -> And I should see application edit link on dashboard
rspec ./spec/acceptance/application_form_creation.feature:6 # Creating application forms I see application links on dashboard When I go to dashboard -> Then I should see innovation application link -> And I should see international trade application link -> And I should see sustainable development application link
rspec ./spec/acceptance/application_form_creation.feature:17 # Creating application forms I'm able to create international trade form When I create international trade form -> Then I should see qae form -> And I should see application edit link on dashboard
rspec ./spec/acceptance/application_form_creation.feature:12 # Creating application forms I'm able to create innovation form When I create innovation form -> Then I should see qae form -> And I should see application edit link on dashboard
rspec ./spec/models/form_answer_state_machine_spec.rb:69 # FormAnswerStateMachine#perform_transition after the deadline as Assessor can change state only to allowed
rspec ./spec/models/form_answer_state_machine_spec.rb:53 # FormAnswerStateMachine#trigger_deadlines deadline expired applications in progress automatically changes state to `not_submitted`
rspec ./spec/models/form_answer_state_machine_spec.rb:32 # FormAnswerStateMachine#trigger_deadlines deadline expired assessment_in_progress -> withdrawn sends notification for the Lead Assessor
rspec ./spec/models/form_answer_state_machine_spec.rb:43 # FormAnswerStateMachine#trigger_deadlines deadline expired applications submitted automatically changes state to `assessment_in_progress`
Randomized with seed 32450

**Comment by dreamfall** [comment]
Most of the errors are fixed now.

**Comment by RuslanHamidullin** [comment]
Yeah Green Days :green_apple:
